// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANA8ueOpstL8f-CZZjGv8yn-lfbGPMw5w',
    appId: '1:731884289139:web:67fe9fd917352efe21fe06',
    messagingSenderId: '731884289139',
    projectId: 'happyhourtracker',
    authDomain: 'happyhourtracker.firebaseapp.com',
    storageBucket: 'happyhourtracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGzwZVsOwOkNNPmmOQisR-9pA7syVay-4',
    appId: '1:731884289139:android:184188e413ff76d221fe06',
    messagingSenderId: '731884289139',
    projectId: 'happyhourtracker',
    storageBucket: 'happyhourtracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL1bWjm6oDAhA79gjZu4hp4snL3iAjNBU',
    appId: '1:731884289139:ios:eb8847a35bed739421fe06',
    messagingSenderId: '731884289139',
    projectId: 'happyhourtracker',
    storageBucket: 'happyhourtracker.firebasestorage.app',
    iosBundleId: 'com.example.happyHourTracker',
  );
}
